service: esteemed-profile

# Configuration variables
custom:
  secrets:
    slackToken: ${file(secrets.yml):slackToken}
    slackTokenBot: ${file(secrets.yml):slackTokenBot}
    slackSigning: ${file(secrets.yml):slackSigning}
    allowedChannels: ${file(secrets.yml):allowedChannels}
    firebaseApp: ${file(secrets.yml):firebaseApp}
    travisToken: ${file(secrets.yml):travisToken}
    googleMaps: ${file(secrets.yml):googleMaps}
    slackSlashCommandHook: ${file(secrets.yml):slackSlashCommandHook}

  ngrokTunnel:
    tunnels:
      - port: 3000

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_TOKEN: ${self:custom.secrets.slackToken}
    SLACK_TOKEN_BOT: ${self:custom.secrets.slackTokenBot}
    SLACK_SIGNING_SECRET: ${self:custom.secrets.slackSigning}
    SLACK_CHANNELS: ${self:custom.secrets.allowedChannels}
    FIREBASE_APP: ${self:custom.secrets.firebaseApp}
    TRAVIS_TOKEN: ${self:custom.secrets.travisToken}
    GOOGLE_MAPS: ${self:custom.secrets.googleMaps}
    SLACK_SLASH_COMMAND_HOOK: ${self:custom.secrets.slackSlashCommandHook}

functions:
  getConfiguration:
    handler: src/configuration.handler
    events:
      - http:
          path: config
          method: get
          cors: true
  getProfiles:
    handler: src/profiles.handler
    events:
      - http:
          path: profiles
          method: get
          cors: true
  getJobs:
    handler: src/jobs.handler
    events:
      - http:
          path: jobs
          method: get
          cors: true
  getProfileDialog:
    handler: src/profileDialog.handler
    events:
      - http:
          path: dialog
          method: post
          cors: true
  slackEvents:
    handler: src/slackEvents.handler
    events:
      - http:
          path: slackEvents
          method: post
          cors: true
  commandProfile:
    handler: src/slashCommands/profile.handler
    events:
      - http:
          path: command_profile
          method: post
          cors: true
  commandLatestProfiles:
    handler: src/slashCommands/latest_profiles.handler
    events:
      - http:
          path: command_latest_profiles
          method: post
          cors: true
  slashDirectory:
    handler: src/util/slashDir.handler
    events:
      - http:
          path: command_jobs
          method: post
          cors: true
  addJobs:
    handler: src/util/redirectDir.handler
    events:
      - http:
          path: slash_command_redirect
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-ngrok-tunnel
